### ISSUE TITLE
anybody getting this issues?

### ISSUE THREAD

**Issue by wiormax** [DRM-Scripts/DRMPHP#1]
[Tue Apr 11 17:02:15.260212 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Trying to access array offset on value of type null in /var/www/html/panel/_app.php on line 502, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.885670 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Undefined index: SearchChanName in /var/www/html/panel/index.php on line 47, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.885777 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Undefined index: SearchMPDUrl in /var/www/html/panel/index.php on line 53, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.886246 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Undefined index: SearchCatName in /var/www/html/panel/index.php on line 59, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.886309 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Undefined index: search in /var/www/html/panel/_app.php on line 117, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.886328 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Undefined variable: Cond1 in /var/www/html/panel/_app.php on line 131, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.886347 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Undefined variable: Cond2 in /var/www/html/panel/_app.php on line 131, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.886361 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Undefined variable: Cond3 in /var/www/html/panel/_app.php on line 131, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.887211 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Trying to access array offset on value of type null in /var/www/html/panel/index.php on line 131, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.887258 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Trying to access array offset on value of type null in /var/www/html/panel/index.php on line 131, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.887270 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Trying to access array offset on value of type null in /var/www/html/panel/index.php on line 132, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.887291 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Trying to access array offset on value of type null in /var/www/html/panel/index.php on line 133, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.887302 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Trying to access array offset on value of type null in /var/www/html/panel/index.php on line 134, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:18.887311 2023] [php7:notice] [pid 1488] [client 192.168.1.27:65285] PHP Notice:  Trying to access array offset on value of type null in /var/www/html/panel/index.php on line 134, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:21.596972 2023] [php7:warn] [pid 1488] [client 192.168.1.27:65285] PHP Warning:  unlink(/var/www/html/download/test1/aria): Is a directory in /var/www/html/panel/_app.php on line 383, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:21.597012 2023] [php7:warn] [pid 1488] [client 192.168.1.27:65285] PHP Warning:  unlink(/var/www/html/download/test1/hls): Is a directory in /var/www/html/panel/_app.php on line 383, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:21.597029 2023] [php7:warn] [pid 1488] [client 192.168.1.27:65285] PHP Warning:  unlink(/var/www/html/download/test1/log): Is a directory in /var/www/html/panel/_app.php on line 383, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:21.597043 2023] [php7:warn] [pid 1488] [client 192.168.1.27:65285] PHP Warning:  unlink(/var/www/html/download/test1/seg): Is a directory in /var/www/html/panel/_app.php on line 383, referer: http://192.168.1.82/panel/index.php
[Tue Apr 11 17:02:21.597074 2023] [php7:warn] [pid 1488] [client 192.168.1.27:65285] PHP Warning:  unlink(/var/www/html/download/test1/stream): Is a directory in /var/www/html/panel/_app.php on line 383, referer: http://192.168.1.82/panel/index.php

**Comment by DRM-Scripts** [comment]
Please see updated install instructions, this should resolve your issue.
