### ISSUE TITLE
Buttons and drop down menu not working

### ISSUE THREAD

**Issue by Dudik0FF** [DRM-Scripts/DRMPHP#11]
After yesterday's update 05/30/2023, all buttons stopped working, and you can't click on the drop-down menu to change the password and exit the panel. It looks like JS is broken.
p.s. FlussCrack =)

**Comment by DRM-Scripts** [comment]
We’ve pushed a fix overnight. Please test and let us know 👍

**Comment by Dudik0FF** [comment]
Does not work
https://prnt.sc/8FrNk6xr19vU
https://prnt.sc/xuaw9xQ1_tPt

**Comment by DRM-Scripts** [comment]
> Does not work https://prnt.sc/8FrNk6xr19vU https://prnt.sc/xuaw9xQ1_tPt

I'd advise clearing cache as i've just installed fresh using the installer and as you can see from the image (using chrome).


https://github.com/DRM-Scripts/DRMPHP/assets/85300094/e459d301-c392-4d42-b9bf-edce889db558

**Comment by emergildo** [comment]
I am having the same problem, and I just installed Fresh. No button works for me. Is not a cached problem, fresh install and tested in Incognito Chrome. The error is the same as mentioned: 

**index.php:372 Uncaught ReferenceError: DeleteChannel is not defined
    at HTMLAnchorElement.onclick**

**Comment by Dudik0FF** [comment]
I tried replacing the whole folder assets the problem has not been fixed, all the php files have been replaced and the buttons have been working

**Comment by Dudik0FF** [comment]
If necessary, I can replace 1 file and find the file in which the error

**Comment by DRM-Scripts** [comment]
> If necessary, I can replace 1 file and find the file in which the error

It’s trying to work out what’s causing the issue for some people and not. Will continue to investigate

**Comment by DRM-Scripts** [comment]
> If necessary, I can replace 1 file and find the file in which the error

If you have found the file at fault let us know, as seems there is some other little bugs in the works which causes a few things to not load properly.

**Comment by DRM-Scripts** [comment]
> If necessary, I can replace 1 file and find the file in which the error

Please pull the latest and try now.

**Comment by serch-69** [comment]
Hi,

Anyone can support me how to fix this error? Driver not found...

![parse error](https://github.com/DRM-Scripts/DRMPHP/assets/135591797/3040e7d5-eb0c-478d-ab32-124b0790f405)
