### ISSUE TITLE
Streams Buffering

### ISSUE THREAD

**Issue by moutamared** [DRM-Scripts/DRMPHP#12]
Streams keeps buffering each few seconds / minutes
i've tried it directly from ffmpeg and works just fine, but it deosn't works stable with the panel

Thank you.

**Comment by DRM-Scripts** [comment]
Going to need more info than that bud.

like what stream? Where is the server located etc… need as much info as possible so can try replicate.

**Comment by moutamared** [comment]
i am trying Z.A.P.I.T.V streams ( ENDFAMILIA and ESCAPE TV ) and the server is located in France.
it works for few seconds, and buffer and it continue working.
