### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by Hambuchser** [DRM-Scripts/DRMPHP#15]
Iam still use server on He*tzner DC with Ubuntu 18

if i install the script i get this error:
Error!: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)

i tried other users and passwords i dont find any solution

**Comment by DRM-Scripts** [comment]
Check that _db.php has the correct details, if using the installer this shouldn't be an issue.

**Comment by Dudik0FF** [comment]
During installation, you entered the data incorrectly. If you need help with installation I'm always happy to help. My telegram https://t.me/FlussCrack
