### ISSUE TITLE
Doesn't parse the channel

### ISSUE THREAD

**Issue by Dudik0FF** [DRM-Scripts/DRMPHP#17]
Can't parse mpd file data, has a proxy. Next to the test, I installed MPDPlayer v3, registered the same channel and proxy, and everything works fine in it. Proxy without login and password. I also wanted to know what types of proxies are suitable? http socks?
https://prnt.sc/tXI8AmNgZBtg

**Comment by Dudik0FF** [comment]
I'm sorry, I figured it out myself, you just can't delete the user agent in the settings
https://prnt.sc/oThFAhBE9Tgs

**Comment by Dudik0FF** [comment]
Now won't start streaming
[hls @ 0x6187b00] Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' (9000000) and 'probesize' (9000000) options
Input #0, hls, from '/var/www/html/download/Canal+_Sport_1/stream/index.m3u8':
  Duration: N/A, start: 14738.398544, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp
    Metadata:
      variant_bitrate : 0
[hls @ 0x6253bc0] sample rate not set
[out#0/hls @ 0x62d4a80] Could not write header (incorrect codec parameters ?): Invalid argument
[aost#0:1/copy @ 0x619b840] Error initializing output stream: 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times

**Comment by DRM-Scripts** [comment]
> Now won't start streaming
> [hls @ 0x6187b00] Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp): unspecified sample rate
> Consider increasing the value for the 'analyzeduration' (9000000) and 'probesize' (9000000) options
> Input #0, hls, from '/var/www/html/download/Canal+_Sport_1/stream/index.m3u8':
> Duration: N/A, start: 14738.398544, bitrate: N/A
> Program 0
> Metadata:
> variant_bitrate : 0
> Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
> Metadata:
> variant_bitrate : 0
> Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp
> Metadata:
> variant_bitrate : 0
> [hls @ 0x6253bc0] sample rate not set
> [out#0/hls @ 0x62d4a80] Could not write header (incorrect codec parameters ?): Invalid argument
> [aost#0:1/copy @ 0x619b840] Error initializing output stream:
> Stream mapping:
> Stream #0:0 -> #0:0 (copy)
> Stream #0:1 -> #0:1 (copy)
> Last message repeated 1 times

Hi mate, due to you clearly copying all our files and then posting on your GH, I’ll close this issue and allow you to fix it on your own.

👍
