### ISSUE TITLE
delay

### ISSUE THREAD

**Issue by same7n** [DRM-Scripts/DRMPHP#22]
hi mate,
thanx for your efforts you  make a great job 
please if you can fix delay in starting channel now it can takes 2 min to start

and delay in streaming i can see channels have delay more than one min 

so sorry for bothering you and i hope you can fix this bugs

thanx

**Comment by DRM-Scripts** [comment]
we are currently working on a new parser/downloader that should hopefully resolve this issue.

**Comment by same7n** [comment]
many thanx for your replay and i have another problem i do not know if any one face the same problem or not

streams go off randomly after a while i do not know why?!!!

**Comment by DRM-Scripts** [comment]
> many thanx for your replay and i have another problem i do not know if any one face the same problem or not
> 
> streams go off randomly after a while i do not know why?!!!

Are you playing the streams direct to sau XUI? I'd suggest using fluss as a middleman.

**Comment by same7n** [comment]
i did not add streams to any panel yet i just play them on drm panel and after a while thy go off i really do not know the reason

**Comment by same7n** [comment]
i tried a lot of things like i changed the ffmpeg binary and , modified the ffmpeg command all i get that i do no have freeze in channels and i reduce latency but the only problem for me now just the streams go off after a while!!!!

**Comment by same7n** [comment]
hi mate,

i found streams stopped because this error Cannot get correct #EXTINF value of segment
any solution?

**Comment by DRM-Scripts** [comment]
As mentioned we are adding multiple options in the upcoming update which helps overcome this issue. 

No eta currently as we are all quite busy but hopefully should be too long.
