### ISSUE TITLE
blank web

### ISSUE THREAD

**Issue by same7n** [DRM-Scripts/DRMPHP#23]
thanx again for your great job mate 

the new installation after install on ubuntu 18.06 the panel give blank web after login in dashboard.php

thanx

**Comment by micmaree** [comment]
Go to /etc/php/7.2/apache2/php.ini   and enable short_open_tags   switch from Off to On , after that  service apache2 restart

**Comment by same7n** [comment]
many thanx for your replay its ok now after your solution

thanx
