### ISSUE TITLE
Streams error

### ISSUE THREAD

**Issue by chadb3887** [DRM-Scripts/DRMPHP#24]
**Describe the bug**
Load in a Channel eg keys/mpd url
**To Reproduce**
Load/press play and wait example :skygo  channelE4 with in a hour or 2 the channel will just say error.

ffmpeg log
hls @ 0x7048940] Skip ('#EXT-X-VERSION:3')
[hls @ 0x7048940] Skip ('#EXT-X-ALLOW-CACHE:YES')
[hls @ 0x7048940] Skip ('#EXT-X-VERSION:3')
[hls @ 0x7048940] Skip ('#EXT-X-ALLOW-CACHE:YES')
[hls @ 0x7048940] Skip ('#EXT-X-VERSION:3')
[hls @ 0x7048940] Skip ('#EXT-X-ALLOW-CACHE:YES')

**Expected behavior**
Should stay online 

**Screenshots**
N/a

**Desktop (please complete the following information):**
 OS: Ubuntu 20.04

**Smartphone (please complete the following 
n/a

**Additional context**
N/a.

**Comment by DRM-Scripts** [comment]
We are looking at the error and should possibly push a fix soon or more than likely in next release

**Comment by chadb3887** [comment]
Nice one cheers Sent from my iPhoneOn 17 Jul 2023, at 10:25, DRM-Scripts ***@***.***> wrote:﻿
We are looking at the error and should possibly push a fix soon or more than likely in next release

**Comment by Dazzler1985** [comment]
Streams are given as error because they dont write to the /download/channelname/hls directory thats why you also cant preview.
It seems streams / hls are in /download/channelname/stream directory.

If you edit your m3u8 url to that path you can watch the stream .

So the error and not able to preview are because streams are outputted in /stream and not /hls .

**Comment by DRM-Scripts** [comment]
> Streams are given as error because they dont write to the /download/channelname/hls directory thats why you also cant preview. It seems streams / hls are in /download/channelname/stream directory.
> 
> If you edit your m3u8 url to that path you can watch the stream .
> 
> So the error and not able to preview are because streams are outputted in /stream and not /hls .
> 
> edit : actually it seems if you wait a couple minutes also the hls directory is used it seems it creates 2 versions of stream 1 in /hls and 1 in /stream why that is i dont know.

its a bug shhhh lol. Its been reported to us and has been fixed in a build we are currently testing.

**Comment by chadb3887** [comment]
🤣🤣 ok shhhh don’t tell no oneSent from my iPhoneOn 23 Jul 2023, at 22:05, DRM-Scripts ***@***.***> wrote:﻿

Streams are given as error because they dont write to the /download/channelname/hls directory thats why you also cant preview. It seems streams / hls are in /download/channelname/stream directory.
If you edit your m3u8 url to that path you can watch the stream .
So the error and not able to preview are because streams are outputted in /stream and not /hls .
edit : actually it seems if you wait a couple minutes also the hls directory is used it seems it creates 2 versions of stream 1 in /hls and 1 in /stream why that is i dont know.

its a bug shhhh lol. Its been reported to us and has been fixed in a build we are currently testing.
