### ISSUE TITLE
pls chack and fix ubuntu 18 instalation 

### ISSUE THREAD

**Issue by senkron24** [DRM-Scripts/DRMPHP#29]
using 
ubuntu 18 
php 7.4 cannot be installed becouse the instalation script try not 7.2 he start work with 7.4 need fix 

i have try to installed manuely with php 7.2 
than get mysql problems 
thare a lot problems with ubuntu 18 need fix 

thanks for the work ...

**Comment by DRM-Scripts** [comment]
which installer are you using? As the current one has 7.2 for U18.04

**Comment by senkron24** [comment]
thare its only one 

https://github.com/DRM-Scripts/DRMPHP/blob/master/readme-1804.txt

and this its insaide with 7.,4 :(

i have to use the beta ?

https://github.com/DRM-Scripts/DRMPHP/blob/master/installer-beta.sh

**Comment by senkron24** [comment]
now installed no problem 
bud i think its not working with xtream codes togther becosue curl 

its thare any way to fix this thad works with xtream codes in same server ?

its exackt i think 
libcurl4 and php7.2-curl
bud xtream codes working with libcurl3

**Comment by DRM-Scripts** [comment]
> now installed no problem bud i think its not working with xtream codes togther becosue curl
> 
> its thare any way to fix this thad works with xtream codes in same server ?
> 
> its exackt i think libcurl4 and php7.2-curl bud xtream codes working with libcurl3

Only advise separate servers
